export const API_TYPES = ["adjective", "animal", "noun"];
export const API_URL = "https://random-word-form.repl.co/random/";
export const RESET = "reset";
export const RANDOM = "random";
export const MAX_TRIES = 5;
export const MAX_LETTERS = 8;
export const CURRENT = 0;
export const NEXT = 1;
export const PREV = -1;
